const {test,expect}=require('@playwright/test');
const {LIVE,hostInfo,openWorkbench}=require('../helpers/workbench');
test.skip(!process.env.CLAT_PLG4_NUMERIC_FIXTURE,'requires explicitly signed network staging');
test('signed WASM search installs with exact-origin consent, invokes, and uninstalls',async({page})=>{
 test.setTimeout(360000);
 const id='io.artec.dsh-official-web-wasm';
 const catalog=require('node:fs').readFileSync(process.env.CLAT_PLG4_CATALOG,'utf8');
 expect(JSON.parse(catalog).packages[0].manifestVersion).toBe(2);
 await page.route('https://pi.at.cn/catalog.json',route=>route.fulfill({contentType:'application/json',body:catalog}));
 await openWorkbench(page,hostInfo('plugin-market'));
 await page.click('#market-open');
 await page.getByRole('button',{name:'Install…',exact:true}).click();
 await expect(page.locator('.plugin-review')).toContainText('Network restricted to:',LIVE);
 await expect(page.locator('.plugin-review')).not.toContainText('Native executable');
 const install=page.locator('.plugin-review').getByRole('button',{name:'Install',exact:true});
 await expect(install).toBeDisabled();
 await page.getByLabel('DeepSeek API key',{exact:true}).fill('private-fixture-key');
 await page.getByLabel('Provider fixture options',{exact:true}).fill(JSON.stringify({baseURL:process.env.CLAT_PLG4_NUMERIC_FIXTURE+'/anthropic/v1'}));
 await page.locator('.plugin-consent input').check();
 const committed=page.waitForResponse(r=>r.url().endsWith('/api/plugin.commit'),{timeout:240000});
 await install.click();expect((await(await committed).json()).ok).toBe(true);
 const installed=page.locator(`.plugin-installed [data-plugin-id="${id}"]`);
 await expect(installed).toContainText('Enabled',LIVE);
 await page.click('#market-close');
 await page.fill('#prompt','perform fixture search');await page.click('#send');
 for (let approval=0;approval<3;approval++) await page.getByRole('button',{name:'Allow',exact:true}).click({timeout:60000});
 await expect(page.locator('#cancel')).toBeHidden({timeout:90000});
 await expect(page.locator('.msg.assistant').last()).toContainText('done',LIVE);
 await expect(page.locator('#transcript')).toContainText('CLAT PLG-2 fixture',LIVE);
 expect(await page.locator('#transcript').textContent()).not.toContain('private-fixture-key');
 expect(await page.evaluate(()=>JSON.stringify(localStorage))).not.toContain('private-fixture-key');
 await page.click('#market-open');
 await installed.getByRole('button',{name:'Uninstall',exact:true}).click();
 await expect(installed).toHaveCount(0,LIVE);
 expect((await page.evaluate(()=>rpc('plugin.list',{}))).installed).toEqual([]);
});
