//! Cross-implementation checks against bytes generated by Node itself
//! (`node:zlib` zstd + `JSON.stringify`, the exact primitives DSH uses).
//! The test self-skips unless the fixture directory exists, so normal CI
//! runs are unaffected; `docs/research/dsh-session-compatibility.md` §14
//! records the regen command.

#[cfg(test)]
mod tests {
    use crate::session::chunk_packing::decode_storage_record;
    use crate::session::event::SessionEvent;
    use crate::session::header::SessionHeader;
    use crate::session::id::SessionId;
    use crate::session::zstd_frames;

    const FIXTURES: &str = "/tmp/clat-interop";

    fn fixture(name: &str) -> Option<Vec<u8>> {
        let path = std::path::Path::new(FIXTURES).join(name);
        std::fs::read(path).ok()
    }

    #[test]
    fn node_generated_frames_scan_decode_and_parse() {
        let Some(log) = fixture("log-two-frames.bin") else {
            return;
        };
        let expected_header_frame = fixture("header-frame.bin").expect("partial fixture set");
        let expected_body_frame = fixture("body-frame.bin").expect("partial fixture set");

        let scan = zstd_frames::scan_frames(&log, usize::MAX).expect("scan node frames");
        assert_eq!(scan.torn_start, None);
        assert_eq!(scan.frames.len(), 2);
        assert_eq!(scan.frames[0].len(), expected_header_frame.len());
        assert_eq!(scan.frames[1].len(), expected_body_frame.len());

        let header_plain =
            zstd_frames::decompress_frame_capped(&log[scan.frames[0].clone()], usize::MAX)
                .expect("decode node header frame");
        let golden_header = fixture("header-line.txt").expect("fixture");
        assert_eq!(header_plain, golden_header, "checksum-verified decode");

        let header = SessionHeader::from_line(
            std::str::from_utf8(&header_plain[..header_plain.len() - 1]).expect("utf8"),
        )
        .expect("parse")
        .expect("header");
        assert_eq!(
            header.id,
            SessionId::new("018f2a64-9d3f-7cde-8123-9a4f2b6c0001")
        );
        assert_eq!(
            header.cwd.as_deref(),
            Some("/Users/deng/Documents/GitHub/clat")
        );

        let body_plain =
            zstd_frames::decompress_frame_capped(&log[scan.frames[1].clone()], usize::MAX)
                .expect("decode node body frame");
        let lines: Vec<&str> = std::str::from_utf8(&body_plain)
            .expect("utf8")
            .trim_end_matches('\n')
            .split('\n')
            .collect();
        assert_eq!(lines.len(), 2);
        let event: SessionEvent = serde_json::from_str(lines[0]).expect("event parses");
        assert_eq!(event.event_type, "user/message");
        assert_eq!(
            event.data["content"][0]["text"],
            "héllo \"quoted\" \\ back /slash\ttab"
        );
        let expanded = decode_storage_record(serde_json::from_str(lines[1]).expect("row value"))
            .expect("row expands");
        assert_eq!(expanded.len(), 3);
        assert_eq!(expanded[2].data["chunk"]["text"], "lo");
    }

    #[test]
    fn rust_serialization_matches_node_json_stringify_bytes() {
        let Some(golden_event) = fixture("event-line.txt") else {
            return;
        };
        let Some(golden_row) = fixture("row-line.txt") else {
            return;
        };
        let event: SessionEvent = serde_json::from_slice(&golden_event).expect("parse golden");
        let wire = serde_json::to_string(&event).expect("serialize");
        assert_eq!(
            wire.as_bytes(),
            &golden_event[..],
            "serde must reproduce JSON.stringify bytes (field order + escaping)"
        );
        let row: crate::session::chunk_packing::ChunkRow =
            serde_json::from_slice(&golden_row).expect("parse golden row");
        let row_wire = serde_json::to_string(&row).expect("serialize row");
        assert_eq!(row_wire.as_bytes(), &golden_row[..]);
    }

    #[test]
    fn rust_frames_decode_by_node() {
        // Produce a frame here; the Node side of the check runs in the
        // fixture script. We at least assert our frame scans+decodes and
        // write it out for the reverse verification step.
        let plain = b"{\"type\":\"session\"}\n";
        let frame = zstd_frames::compress_frame(plain).expect("compress");
        let scan = zstd_frames::scan_frames(&frame, 1).expect("scan");
        assert_eq!(scan.frames.len(), 1);
        assert_eq!(
            zstd_frames::decompress_frame_capped(&frame, usize::MAX).expect("decode"),
            plain
        );
        if std::path::Path::new(FIXTURES).is_dir() {
            let _ = std::fs::write(
                std::path::Path::new(FIXTURES).join("rust-frame.bin"),
                &frame,
            );
        }
    }

    /// Foreign-produced events (Node primitives, JSON.stringify field order)
    /// replay through the adapter without panicking: the user message maps,
    /// and the packed chunk rows expand into ignorable `assistant/chunk`
    /// events that land on the skip list.
    #[test]
    fn node_generated_events_replay() {
        let Some(log) = fixture("log-two-frames.bin") else {
            return;
        };
        let scan = zstd_frames::scan_frames(&log, usize::MAX).expect("scan node frames");
        let body_plain =
            zstd_frames::decompress_frame_capped(&log[scan.frames[1].clone()], usize::MAX)
                .expect("decode node body frame");
        let lines: Vec<&str> = std::str::from_utf8(&body_plain)
            .expect("utf8")
            .trim_end_matches('\n')
            .split('\n')
            .collect();
        let mut events = vec![serde_json::from_str::<SessionEvent>(lines[0]).expect("event")];
        for line in &lines[1..] {
            let row: serde_json::Value = serde_json::from_str(line).expect("row value");
            events.extend(decode_storage_record(row).expect("row expands"));
        }
        let replay = crate::session::replay::ReplayAdapter::fold(&events);
        assert_eq!(
            replay.len(),
            1,
            "one user message, chunks skipped: {replay:?}"
        );
        assert!(matches!(
            &replay[0],
            crate::session::replay::ReplayEvent::UserMessage { text, .. }
                if text.contains("héllo")
        ));
    }
}
